/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * 이커머스 플랫폼 API
 * 쇼핑·주문·결제 기능을 제공하는 이커머스 플랫폼 API
 */
export interface ComLoopersInterfacesApiUserUserV1DtoJoinRequest {
  /** @pattern ^[a-zA-Z0-9]{1,10}$ */
  loginId: string;
  /** @pattern ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ */
  email: string;
  /** @pattern ^([MF])$ */
  gender: string;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  birth: string;
}

export type ComLoopersInterfacesApiApiResponseMetadataResult =
  (typeof ComLoopersInterfacesApiApiResponseMetadataResult)[keyof typeof ComLoopersInterfacesApiApiResponseMetadataResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComLoopersInterfacesApiApiResponseMetadataResult = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
} as const;

export interface ComLoopersInterfacesApiApiResponseMetadata {
  result?: ComLoopersInterfacesApiApiResponseMetadataResult;
  errorCode?: string;
  message?: string;
}

export interface ComLoopersInterfacesApiApiResponseComLoopersInterfacesApiUserUserV1DtoUserResponse {
  meta?: ComLoopersInterfacesApiApiResponseMetadata;
  data?: ComLoopersInterfacesApiUserUserV1DtoUserResponse;
}

export interface ComLoopersInterfacesApiUserUserV1DtoUserResponse {
  id?: number;
  loginId?: string;
  email?: string;
  gender?: string;
  birth?: string;
}

export interface ComLoopersInterfacesApiPointPointV1DtoChargeRequest {
  /** @minimum 1 */
  amount: number;
}

export interface ComLoopersInterfacesApiApiResponseComLoopersInterfacesApiPointPointV1DtoPointResponse {
  meta?: ComLoopersInterfacesApiApiResponseMetadata;
  data?: ComLoopersInterfacesApiPointPointV1DtoPointResponse;
}

export interface ComLoopersInterfacesApiPointPointV1DtoPointResponse {
  userId?: number;
  amount?: number;
}

export interface ComLoopersApplicationProductProductInfoMain {
  id?: number;
  name?: string;
  price?: number;
  likeCount?: number;
  brandName?: string;
  brandDesc?: string;
  quantity?: number;
}

export interface ComLoopersInterfacesApiApiResponseComLoopersInterfacesApiProductProductV1DtoProductResponseSummary {
  meta?: ComLoopersInterfacesApiApiResponseMetadata;
  data?: ComLoopersInterfacesApiProductProductV1DtoProductResponseSummary;
}

export interface ComLoopersInterfacesApiProductProductV1DtoProductResponseSummary {
  products?: ComLoopersApplicationProductProductInfoMain[];
  page?: number;
  size?: number;
}

export interface ComLoopersInterfacesApiApiResponseComLoopersInterfacesApiProductProductV1DtoProductResponseDetail {
  meta?: ComLoopersInterfacesApiApiResponseMetadata;
  data?: ComLoopersInterfacesApiProductProductV1DtoProductResponseDetail;
}

export interface ComLoopersInterfacesApiProductProductV1DtoProductResponseDetail {
  id?: number;
  name?: string;
  price?: number;
  likeCount?: number;
  brandName?: string;
  brandDesc?: string;
  quantity?: number;
}

export interface ComLoopersInterfacesApiApiResponseComLoopersInterfacesApiBrandBrandV1DtoBrandResponse {
  meta?: ComLoopersInterfacesApiApiResponseMetadata;
  data?: ComLoopersInterfacesApiBrandBrandV1DtoBrandResponse;
}

export interface ComLoopersInterfacesApiBrandBrandV1DtoBrandResponse {
  id?: number;
  name?: string;
  description?: string;
}

export type ChargeHeaders = {
  /**
   * 사용자 식별 USER_ID 헤더
   */
  "X-USER-ID": number;
};

export type GetUserInfoHeaders = {
  /**
   * 사용자 식별 USER_ID 헤더
   */
  "X-USER-ID": number;
};

export type GetListParams = {
  brandId?: number;
  sort?: GetListSort;
  /**
   * @minimum 0
   */
  page?: number;
  /**
   * @minimum 10
   * @maximum 50
   */
  size?: number;
};

export type GetListSort = (typeof GetListSort)[keyof typeof GetListSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetListSort = {
  LATEST: "LATEST",
  PRICE_ASC: "PRICE_ASC",
  LIKES_DESC: "LIKES_DESC",
} as const;

export type GetPointHeaders = {
  /**
   * 사용자 식별 USER_ID 헤더
   */
  "X-USER-ID": number;
};
